AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Resources for Lambda Dagger Template App.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 20

Resources:
    SimpleLoggingHandler:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/lambda-dagger-template-1.0.jar
            Handler: lambdas.SimpleLoggingHandler::handleRequest
            Runtime: java8
            Events:
                GetData:
                    Type: Api
                    Properties:
                        Path: /logger
                        Method: GET

    DynamoDBMapperHandler:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: target/lambda-dagger-template-1.0.jar
            Handler: lambdas.DynamoDBMapperHandler::handleRequest
            Runtime: java8
            Events:
                GetData:
                    Type: Api
                    Properties:
                        Path: /item
                        Method: GET
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: 'DaggerExampleTable'

    DataTable:
        Type: AWS::DynamoDB::Table
        Properties:
            AttributeDefinitions:
                - AttributeName: "ItemId"
                  AttributeType: "S"
            KeySchema:
                - AttributeName: "ItemId"
                  KeyType: "HASH"
            ProvisionedThroughput:
                ReadCapacityUnits: "5"
                WriteCapacityUnits: "5"
            TableName: "DaggerExampleTable"